In [32]:
#Step 1: Data Importing & Cleaning
import pandas as pd

main_df = pd.read_csv("owid_climate_data.csv")
main_df.head()
main_df.index
main_df.columns
main_df.info
main_df.head()
main_df.isnull()

,Country Name,Country Code,Year,CO2 Emissions Per Capita,Annual Temperature Anomaly
0,False,False,False,False,False
1,False,False,False,False,False
2,False,False,False,False,False
3,False,False,False,False,False
4,False,False,False,False,False
...,...,...,...,...,...
26177,False,False,False,False,False
26178,False,False,False,False,False
26179,False,False,False,False,False
26180,False,False,False,False,False
26181,False,False,False,False,False

In [33]:
main_df.dropna(subset=["CO2 Emissions Per Capita", "Annual Temperature Anomaly"])

,Country Name,Country Code,Year,CO2 Emissions Per Capita,Annual Temperature Anomaly
0,Afghanistan,AFG,1949,0.001992,-2.020418
1,Afghanistan,AFG,1950,0.010837,-2.298886
2,Afghanistan,AFG,1951,0.011625,-1.287201
3,Afghanistan,AFG,1952,0.011468,-1.237078
4,Afghanistan,AFG,1953,0.013123,-1.084867
...,...,...,...,...,...
26177,Zimbabwe,ZWE,2019,0.672040,0.878125
26178,Zimbabwe,ZWE,2020,0.547085,0.229293
26179,Zimbabwe,ZWE,2021,0.645915,0.016838
26180,Zimbabwe,ZWE,2022,0.648761,0.035659
26181,Zimbabwe,ZWE,2023,0.683201,0.792851

In [43]:
main_df = df.dropna(subset=["CO2 Emissions Per Capita", "Annual Temperature Anomaly"]) #Drops any NaN values in these two columns

In [44]:
main_df.head(5)

,Country Name,Country Code,Year,CO2 Emissions Per Capita,Annual Temperature Anomaly
0,Afghanistan,AFG,1949,0.001992,-2.020418
1,Afghanistan,AFG,1950,0.010837,-2.298886
2,Afghanistan,AFG,1951,0.011625,-1.287201
3,Afghanistan,AFG,1952,0.011468,-1.237078
4,Afghanistan,AFG,1953,0.013123,-1.084867

In [55]:
#Step 2 Sets & Functions

#Here I make a set of all countries in the dataset
main_df["Country Name"]
countries = main_df["Country Name"] #Set of Countries
countries.drop_duplicates() #Shows a set of all the countries in the CSV, dropping the dupes of each one
#Make a separate dataframe for country name only
country_name_df = df[["Country Name"]].drop_duplicates()
country_name_df
country_name_df.head(50)

                      Country Name
0                      Afghanistan
222                        Albania
330                        Algeria
414                        Andorra
448                         Angola
522                       Anguilla
556            Antigua and Barbuda
714                      Argentina
886                        Armenia
1649                     Australia
1855                       Austria
2027                    Azerbaijan
2111                       Bahamas
2192                       Bahrain
2276                    Bangladesh
2527                       Belarus
2722                       Belgium
2806                        Belize
2880                         Benin
3028                        Bhutan
3133                       Bolivia
3337        Bosnia and Herzegovina
3419                      Botswana
3555                        Brazil
3708                        Brunei
3851                      Bulgaria
3935                  Burkina Faso
4009                       Burundi
4083                      Cambodia
4152                      Cameroon
4367                        Canada
4451                    Cape Verde
4525      Central African Republic
4599                          Chad
4769                         Chile
4886                         China
5054                      Colombia
5138                       Comoros
5203                         Congo
5277                  Cook Islands
5402                    Costa Rica
5486                 Cote d'Ivoire
5606                       Croatia
5772                          Cuba
5930                        Cyprus
6084                       Czechia
6188  Democratic Republic of Congo
6369                       Denmark
6453                      Djibouti
6670            Dominican Republic

In [57]:
#Now to make a separate dataframe for year
main_df["Year"]
year_df = main_df[["Year"]]
year_df

       Year
0      1949
1      1950
2      1951
3      1952
4      1953
...     ...
26177  2019
26178  2020
26179  2021
26180  2022
26181  2023

[14319 rows x 1 columns]

In [58]:
#Combining Country_Name and Year into one DF!
country_name_and_year_range_df = country_name_df.join(year_df)
country_name_and_year_range_df

      Country Name  Year
0      Afghanistan  1949
222        Albania  1940
330        Algeria  1940
414        Andorra  1990
448         Angola  1950
...            ...   ...
25701      Vietnam  1940
25838        World  1940
25913        Yemen  1950
25987       Zambia  1950
26098     Zimbabwe  1940

[187 rows x 2 columns]

In [65]:
#Function that returns all rows for a given country and year range
def get_country_data(df, country, start_year, end_year):
    filtered_country_and_years = df[(df["Country Name"] == country) &
                                    (df["Year"] >= start_year) &
                                    (df["Year"] <= end_year)]
    return filtered_country_and_years
    
#Practice result
result = get_country_data(country_name_and_year_range_df, 'Czechia', 1930, 2020)
print(result)

     Country Name  Year
6084      Czechia  1940